FROM python:3.12

WORKDIR /src
COPY ./app /src

RUN pip install --no-cache-dir -r requirements.txt

#EXPOSE 7860
EXPOSE 8989
#CMD ["python", "gradio_app.py"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8989"]