services:     # Define los servicios que se ejecutarán en contenedores Docker.
  create_models: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).

    build: 
      context: ./jupyter_models
      dockerfile: Dockerfile

    container_name: models_lab
    ports:
      - "8900:8900" 

    volumes:
      - './jupyter_models/app:/src/train_models/app'
      - './models:/src/train_models/app/models'

    command: > 
     bash -c "uv run --with jupyter jupyter lab --ip=0.0.0.0 --port=8900 --allow-root"

    # Define los servicios que se ejecutarán en contenedores Docker.
  # call_models: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).

  #   build: 
  #     context: ./api_read_models
  #     dockerfile: Dockerfile

  #   container_name: models_api_inference
  #   ports:
  #     - "8000:8000" 

  #   volumes:
  #     - './api_read_models/app:/src/uvenv/app'
  #     - './models:/src/uvenv/app/models'

  #   command: "uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
