apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - minio-deployment.yaml
  - mlflow-deployment.yaml
  - postgres-deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: servicios-airflow