# Usa una imagen base con Python 3.10
FROM python:3.10

# Define el directorio de trabajo
WORKDIR /app

# Copia solo los archivos esenciales para instalar dependencias
COPY ./venv/pyproject.toml ./venv/uv.lock ./app/requirements.txt ./

# Instala `uv` y sincroniza las dependencias
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN uv sync --frozen

# Instala dependencias adicionales si es necesario
RUN uv add -r requirements.txt
