services:
  preprocess_data:
    build: 
      context: .
      dockerfile: dockerfile

    container_name: project1

    ports:
      - "8888:8888"  # Ahora coincide con Jupyter Lab

    volumes:
      #- './Proyecto1/app:/app/'  # Solo si necesitas editar código en vivo
      - './app/src:/app/src'  # Solo si necesitas editar código en vivo

    command: >
        bash -c "uv run --with jupyter jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser"
