# services:     # Define los servicios que se ejecutarán en contenedores Docker.
#   preprocess_data: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).

#     build: 
#       context: .
#       dockerfile: dockerfile

#     container_name: project1
#     ports:
#       - "8080:80" 

#     volumes:
#       - './Proyecto1/app:/app/'

#     command: > 
#      bash -c "uv run --with jupyter jupyter lab --ip=0.0.0.0 --port=80 --allow-root"


services:
  preprocess_data:
    build: 
      context: .
      dockerfile: dockerfile

    container_name: project1

    ports:
      - "8888:8888"  # Ahora coincide con Jupyter Lab

    volumes:
      #- './Proyecto1/app:/app/'  # Solo si necesitas editar código en vivo
      - './app:/app/'  # Solo si necesitas editar código en vivo

    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
