apiVersion: v1
kind: Pod
metadata:
  name: socat-proxy
spec:
  containers:
    - name: socat
      image: alpine/socat
      args: ["tcp-listen:8080,fork,reuseaddr", "tcp-connect:inference-models:8989"]
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: socat-service
spec:
  selector:
    name: socat-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30101
  type: NodePort
