version: "3.8"

services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: locust # No funciona con docker swarm -> docker swarm init
    ports:
      - "8089-8094:8089"
    volumes:
      - ./locust_logs.log:/app/locust_logs.log 
    # depends_on:
    #   - 
    environment:
      - LOCUST_HOST=http://inference_models:8989
    #  - REPLICA_COUNT=2
    #  - CPU_LIMIT=1.5
    #  - MEM_LIMIT=1000M
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          memory: 1000M
          cpus: 1.5
    networks:
      - my_shared_network
    privileged: true

networks:
  my_shared_network:
    external: true