version: "3.8"

services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locust
    ports:
      - "8089:8089"
    # depends_on:
    #   - 
    environment:
      - LOCUST_HOST=http://inference_models:8989
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true