services:     # Define los servicios que se ejecutarán en contenedores Docker.
  pinwinos: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).
    build: .  # Indica que Docker debe construir la imagen usando el Dockerfile ubicado en el directorio actual (".").
    container_name: docker-pinwino
    ports:
      - "8000:80" 

    volumes:
      - './app:/src/app' 

    command: >
      sh -c "cd app &&
             uvicorn classification_models_api:app --host 0.0.0.0 --port 80 --reload "

  lab-jupyter: # Nombre del servicio, en este caso es un servicio para ML (Machine Learning).
    build: .  # Indica que Docker debe construir la imagen usando el Dockerfile ubicado en el directorio actual (".").
    container_name: jupyter-ui
    ports:
      - "8080:80" 

    volumes:
      - './app:/src/app' 

    entrypoint: jupyter lab --ip=0.0.0.0 --port=80 --allow-root
