FROM python:3.12

WORKDIR /app/src

COPY . /app/src

RUN pip install --upgrade pip
RUN pip install "jupyter >= 1.0.0" && pip install "jupyterlab >= 4.3.5"
EXPOSE 8888
#CMD ["python","classification_models_api.py"]
CMD ["jupyter","lab","--ip=0.0.0.0","--allow-root"]