FROM apache/airflow:2.6.0

WORKDIR /src
ADD ./train_models /src/train_models
ADD ./app /src/train_models/app

#COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /src/train_models
#RUN uv sync --frozen
#RUN uv add -r app/requirements.txt
RUN pip install -r app/requirements.txt