version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - '80:80'
    volumes:
      - ./data:/data
      - ./main.py:/main.py
    restart: always