apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    io.kompose.network/proyecto3_api_network: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: ogcorzo/prometheus-custom:1.0.5 # Imagen personalizada
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
