name: CI - FastAPI + Docker

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11-slim"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r Taller6/api/requirements.txt
        pip install pytest

    - name: Ejecutar pruebas
      run: |
        pytest Taller6/api/tests/

    - name: Login a DockerHub
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y subir imagen a DockerHub
      if: success()
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/taller6-fastapi-ml-api:latest
